config/routes.rb
Rails.application.routes.draw do
  resources :votos

  resources :candidatos

  resources :partidos

  resources :eleitors

end

app/models/partido.rb
class Partido < ActiveRecord::Base
	has_many :candidato
	paginates_per 3
end

app/controllers/partidos_controller.rb
class PartidosController < ApplicationController
  before_action :set_partido, only: [:show, :edit, :update, :destroy]

  # GET /partidos
  # GET /partidos.json
  def index
    @partidos = Partido.all.page params['page']
  end

  # GET /partidos/1
  # GET /partidos/1.json
  def show
  end

  # GET /partidos/new
  def new
    @partido = Partido.new
  end

  # GET /partidos/1/edit
  def edit
  end

  # POST /partidos
  # POST /partidos.json
  def create
    @partido = Partido.new(partido_params)

    respond_to do |format|
      if @partido.save
        format.html { redirect_to @partido, notice: 'Partido was successfully created.' }
        format.json { render :show, status: :created, location: @partido }
      else
        format.html { render :new }
        format.json { render json: @partido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partidos/1
  # PATCH/PUT /partidos/1.json
  def update
    respond_to do |format|
      if @partido.update(partido_params)
        format.html { redirect_to @partido, notice: 'Partido was successfully updated.' }
        format.json { render :show, status: :ok, location: @partido }
      else
        format.html { render :edit }
        format.json { render json: @partido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partidos/1
  # DELETE /partidos/1.json
  def destroy
    @partido.destroy
    respond_to do |format|
      format.html { redirect_to partidos_url, notice: 'Partido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partido
      @partido = Partido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partido_params
      params.require(:partido).permit(:numero, :nome, :sigla)
    end
end

app/helpers/partidos_helper.rb
module PartidosHelper
end

app/views/partidos/_form.html.erb
<%= form_for(@partido) do |f| %>
  <% if @partido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partido.errors.count, "error") %> prohibited this partido from being saved:</h2>

      <ul>
      <% @partido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sigla %><br>
    <%= f.text_field :sigla %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partidos/edit.html.erb
<h1>Editing partido</h1>

<%= render 'form' %>

<%= link_to 'Show', @partido %> |
<%= link_to 'Back', partidos_path %>

app/views/partidos/index.html.erb
<h1>Listing partidos</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nome</th>
      <th>Sigla</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partidos.each do |partido| %>
      <tr>
        <td><%= partido.numero %></td>
        <td><%= partido.nome %></td>
        <td><%= partido.sigla %></td>
        <td><%= link_to 'Show', partido %></td>
        <td><%= link_to 'Edit', edit_partido_path(partido) %></td>
        <td><%= link_to 'Destroy', partido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= paginate @partidos %>
  </tbody>
</table>

<br>

<%= link_to 'New Partido', new_partido_path %>

app/views/partidos/new.html.erb
<h1>New partido</h1>

<%= render 'form' %>

<%= link_to 'Back', partidos_path %>

app/views/partidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @partido.numero %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @partido.nome %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @partido.sigla %>
</p>

<%= link_to 'Edit', edit_partido_path(@partido) %> |
<%= link_to 'Back', partidos_path %>