config/routes.rb
Rails.application.routes.draw do
  resources :votos

  resources :candidatos

  resources :partidos

  resources :eleitors

end

app/models/eleitor.rb
class Eleitor < ActiveRecord::Base
	has_one :voto
	validates :titulo, presence: true, uniqueness: true
	paginates_per 3
end

app/controllers/eleitors_controller.rb
class EleitorsController < ApplicationController
  before_action :set_eleitor, only: [:show, :edit, :update, :destroy]

  # GET /eleitors
  # GET /eleitors.json
  def index
    @eleitors = Eleitor.all.page params['page']
  end

  # GET /eleitors/1
  # GET /eleitors/1.json
  def show
  end

  # GET /eleitors/new
  def new
    @eleitor = Eleitor.new
  end

  # GET /eleitors/1/edit
  def edit
  end

  # POST /eleitors
  # POST /eleitors.json
  def create
    @eleitor = Eleitor.new(eleitor_params)

    respond_to do |format|
      if @eleitor.save
        EleitorMailer.welcome_email(@eleitor).deliver
        format.html { redirect_to @eleitor, notice: 'Eleitor was successfully created.' }
        format.json { render :show, status: :created, location: @eleitor }
      else
        format.html { render :new }
        format.json { render json: @eleitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eleitors/1
  # PATCH/PUT /eleitors/1.json
  def update
    respond_to do |format|
      if @eleitor.update(eleitor_params)
        format.html { redirect_to @eleitor, notice: 'Eleitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @eleitor }
      else
        format.html { render :edit }
        format.json { render json: @eleitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eleitors/1
  # DELETE /eleitors/1.json
  def destroy
    @eleitor.destroy
    respond_to do |format|
      format.html { redirect_to eleitors_url, notice: 'Eleitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eleitor
      @eleitor = Eleitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eleitor_params
      params.require(:eleitor).permit(:nome, :titulo, :endereco, :telefone, :email)
    end
end

app/helpers/eleitors_helper.rb
module EleitorsHelper
end

app/views/eleitors/_form.html.erb
<%= form_for(@eleitor) do |f| %>
  <% if @eleitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eleitor.errors.count, "error") %> prohibited this eleitor from being saved:</h2>

      <ul>
      <% @eleitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.number_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.number_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eleitors/edit.html.erb
<h1>Editing eleitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @eleitor %> |
<%= link_to 'Back', eleitors_path %>

app/views/eleitors/index.html.erb
<h1>Listing eleitors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Titulo</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eleitors.each do |eleitor| %>
      <tr>
        <td><%= eleitor.nome %></td>
        <td><%= eleitor.titulo %></td>
        <td><%= eleitor.endereco %></td>
        <td><%= eleitor.telefone %></td>
        <td><%= eleitor.email %></td>
        <td><%= link_to 'Show', eleitor %></td>
        <td><%= link_to 'Edit', edit_eleitor_path(eleitor) %></td>
        <td><%= link_to 'Destroy', eleitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
     <%= paginate @eleitors %>

<br>

<%= link_to 'New Eleitor', new_eleitor_path %>

app/views/eleitors/new.html.erb
<h1>New eleitor</h1>

<%= render 'form' %>

<%= link_to 'Back', eleitors_path %>

app/views/eleitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @eleitor.nome %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @eleitor.titulo %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @eleitor.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @eleitor.telefone %>
</p>
<p>
  <strong>Email:</strong>
  <%= @eleitor.email %>
</p>

<%= link_to 'Edit', edit_eleitor_path(@eleitor) %> |
<%= link_to 'Back', eleitors_path %>