config/routes.rb
Rails.application.routes.draw do
  resources :votos

  resources :candidatos

  resources :partidos

  resources :eleitors

end

app/models/voto.rb
class Voto < ActiveRecord::Base
	belongs_to :eleitor
	belongs_to :candidato
	validates_presence_of  :candidato_id
	validates_associated :eleitor, :candidato
	validates :eleitor_id, presence: true, uniqueness: true
	paginates_per 3
end

app/controllers/votos_controller.rb
class VotosController < ApplicationController
  before_action :set_voto, only: [:show, :edit, :update, :destroy]

  # GET /votos
  # GET /votos.json
  def index
    @votos = Voto.all.page params['page']
    render "index"
  end

  # GET /votos/1
  # GET /votos/1.json
  def show
  end

  # GET /votos/new
  def new
    @voto = Voto.new
  end

  # GET /votos/1/edit
  def edit
  end

  # POST /votos
  # POST /votos.json
  def create
    @voto = Voto.new(voto_params)

    respond_to do |format|
      if @voto.save
        format.html { redirect_to @voto, notice: 'Voto was successfully created.' }
        format.json { render :show, status: :created, location: @voto }
      else
        format.html { render :new }
        format.json { render json: @voto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votos/1
  # PATCH/PUT /votos/1.json
  def update
    respond_to do |format|
      if @voto.update(voto_params)
        format.html { redirect_to @voto, notice: 'Voto was successfully updated.' }
        format.json { render :show, status: :ok, location: @voto }
      else
        format.html { render :edit }
        format.json { render json: @voto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votos/1
  # DELETE /votos/1.json
  def destroy
    @voto.destroy
    respond_to do |format|
      format.html { redirect_to votos_url, notice: 'Voto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voto
      @voto = Voto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voto_params
      params.require(:voto).permit(:candidato_id, :eleitor_id, :data)
    end
end

app/helpers/votos_helper.rb
module VotosHelper
end

app/views/votos/_form.html.erb
<%= form_for(@voto) do |f| %>
  <% if @voto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voto.errors.count, "error") %> prohibited this voto from being saved:</h2>

      <ul>
      <% @voto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :candidato_id %><br>
    <%= f.collection_select(:candidato_id ,
    Candidato.order(:numero),:id, :nome) %>
  </div>
  <div class="field">
    <%= f.label :eleitor_id %><br>
    <%= f.collection_select(:eleitor_id ,
    Eleitor.order(:titulo),:id, :nome) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votos/edit.html.erb
<h1>Editing voto</h1>

<%= render 'form' %>

<%= link_to 'Show', @voto %> |
<%= link_to 'Back', votos_path %>

app/views/votos/index.html.erb
<h1>Listing votos</h1>

<table>
  <thead>
    <tr>
      <th>Candidato</th>
      <th>Eleitor</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votos.each do |voto| %>
      <tr>
        <td><%= voto.candidato.nome %></td>
        <td><%= voto.eleitor.nome  %></td>
       
        <td><%= link_to 'Show', voto %></td>
        <td><%= link_to 'Edit', edit_voto_path(voto) %></td>
        <td><%= link_to 'Destroy', voto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
     <%= paginate @votos %>

<br>

<%= link_to 'New Voto', new_voto_path %>

app/views/votos/new.html.erb
<h1>New voto</h1>

<%= render 'form' %>

<%= link_to 'Back', votos_path %>

app/views/votos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candidato:</strong>
  <%= @voto.candidato.nome %>
</p>

<p>
  <strong>Eleitor:</strong>
  <%= @voto.eleitor.nome %>
</p>


<%= link_to 'Edit', edit_voto_path(@voto) %> |
<%= link_to 'Back', votos_path %>